version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: promener
    main: ./main.go
    binary: promener
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jycamier/promener/cmd.version={{.Version}}
      - -X github.com/jycamier/promener/cmd.commit={{.Commit}}
      - -X github.com/jycamier/promener/cmd.date={{.Date}}

archives:
  - id: promener
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'

release:
  github:
    owner: jycamier
    name: promener
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}}-v{{.Version}}"

kos:
  - id: promener
    repositories:
      - ghcr.io/jycamier/promener
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    base_import_paths: true
    main: .
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - name: promener
    repository:
      owner: jycamier
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/jycamier/promener
    description: Generates structured Prometheus metrics code with named parameters and interactive HTML documentation from YAML specifications
    license: Apache-2.0
    commit_author:
      name: goreleaserbot
      email: goreleaser@users.noreply.github.com

#chocolateys:
#  - name: promener
#    owners: jycamier
#    authors: Jean-Yves CAMIER
#    project_url: https://github.com/jycamier/promener
#    url_template: "https://github.com/jycamier/promener/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#    license_url: https://github.com/jycamier/promener/blob/main/LICENSE
#    require_license_acceptance: false
#    project_source_url: https://github.com/jycamier/promener
#    docs_url: https://github.com/jycamier/promener/blob/main/README.md
#    bug_tracker_url: https://github.com/jycamier/promener/issues
#    tags: "prometheus metrics code-generator observability monitoring"
#    summary: Prometheus metrics code generator
#    description: |
#      Promener generates type-safe, organized code for Prometheus metrics from YAML specifications.
#      Supports all metric types, constant labels, environment variables, and HTML documentation generation.
#    release_notes: "https://github.com/jycamier/promener/releases/tag/{{ .Tag }}"
#    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#    source_repo: "https://push.chocolatey.org/"
#    skip_publish: false
