version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: promener
    main: ./main.go
    binary: promener
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jycamier/promener/cmd.version={{.Version}}
      - -X github.com/jycamier/promener/cmd.commit={{.Commit}}
      - -X github.com/jycamier/promener/cmd.date={{.Date}}

archives:
  - id: promener
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'

release:
  github:
    owner: jycamier
    name: promener
  draft: false
  prerelease: auto

brews:
  - name: promener
    repository:
      owner: jycamier
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/jycamier/promener
    description: Generates structured Prometheus metrics code with named parameters and interactive HTML documentation from YAML specifications
    license: Apache-2.0
    install: |
      bin.install "promener"
    test: |
      system "#{bin}/promener version"
    commit_author:
      name: goreleaserbot
      email: goreleaser@users.noreply.github.com
