// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/mock_generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/jycamier/promener/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsGenerator is a mock of MetricsGenerator interface.
type MockMetricsGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsGeneratorMockRecorder
	isgomock struct{}
}

// MockMetricsGeneratorMockRecorder is the mock recorder for MockMetricsGenerator.
type MockMetricsGeneratorMockRecorder struct {
	mock *MockMetricsGenerator
}

// NewMockMetricsGenerator creates a new mock instance.
func NewMockMetricsGenerator(ctrl *gomock.Controller) *MockMetricsGenerator {
	mock := &MockMetricsGenerator{ctrl: ctrl}
	mock.recorder = &MockMetricsGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsGenerator) EXPECT() *MockMetricsGeneratorMockRecorder {
	return m.recorder
}

// GenerateMetrics mocks base method.
func (m *MockMetricsGenerator) GenerateMetrics(spec *domain.Specification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMetrics", spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateMetrics indicates an expected call of GenerateMetrics.
func (mr *MockMetricsGeneratorMockRecorder) GenerateMetrics(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMetrics", reflect.TypeOf((*MockMetricsGenerator)(nil).GenerateMetrics), spec)
}

// MockDIGenerator is a mock of DIGenerator interface.
type MockDIGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockDIGeneratorMockRecorder
	isgomock struct{}
}

// MockDIGeneratorMockRecorder is the mock recorder for MockDIGenerator.
type MockDIGeneratorMockRecorder struct {
	mock *MockDIGenerator
}

// NewMockDIGenerator creates a new mock instance.
func NewMockDIGenerator(ctrl *gomock.Controller) *MockDIGenerator {
	mock := &MockDIGenerator{ctrl: ctrl}
	mock.recorder = &MockDIGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDIGenerator) EXPECT() *MockDIGeneratorMockRecorder {
	return m.recorder
}

// GenerateDI mocks base method.
func (m *MockDIGenerator) GenerateDI(spec *domain.Specification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDI", spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateDI indicates an expected call of GenerateDI.
func (mr *MockDIGeneratorMockRecorder) GenerateDI(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDI", reflect.TypeOf((*MockDIGenerator)(nil).GenerateDI), spec)
}
