// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go
//
// Generated by this command:
//
//	mockgen -source=builder.go -destination=mocks/mock_builder.go -package=mocks TemplateDataBuilder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/jycamier/promener/internal/domain"
	generator "github.com/jycamier/promener/internal/generator"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateDataBuilder is a mock of TemplateDataBuilder interface.
type MockTemplateDataBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateDataBuilderMockRecorder
	isgomock struct{}
}

// MockTemplateDataBuilderMockRecorder is the mock recorder for MockTemplateDataBuilder.
type MockTemplateDataBuilderMockRecorder struct {
	mock *MockTemplateDataBuilder
}

// NewMockTemplateDataBuilder creates a new mock instance.
func NewMockTemplateDataBuilder(ctrl *gomock.Controller) *MockTemplateDataBuilder {
	mock := &MockTemplateDataBuilder{ctrl: ctrl}
	mock.recorder = &MockTemplateDataBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateDataBuilder) EXPECT() *MockTemplateDataBuilderMockRecorder {
	return m.recorder
}

// BuildTemplateData mocks base method.
func (m *MockTemplateDataBuilder) BuildTemplateData(spec *domain.Specification, packageName string) *generator.TemplateData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTemplateData", spec, packageName)
	ret0, _ := ret[0].(*generator.TemplateData)
	return ret0
}

// BuildTemplateData indicates an expected call of BuildTemplateData.
func (mr *MockTemplateDataBuilderMockRecorder) BuildTemplateData(spec, packageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTemplateData", reflect.TypeOf((*MockTemplateDataBuilder)(nil).BuildTemplateData), spec, packageName)
}
