// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/mock_htmlgen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/jycamier/promener/internal/domain"
	htmlgen "github.com/jycamier/promener/internal/htmlgen"
	gomock "go.uber.org/mock/gomock"
)

// MockHTMLGenerator is a mock of HTMLGenerator interface.
type MockHTMLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockHTMLGeneratorMockRecorder
	isgomock struct{}
}

// MockHTMLGeneratorMockRecorder is the mock recorder for MockHTMLGenerator.
type MockHTMLGeneratorMockRecorder struct {
	mock *MockHTMLGenerator
}

// NewMockHTMLGenerator creates a new mock instance.
func NewMockHTMLGenerator(ctrl *gomock.Controller) *MockHTMLGenerator {
	mock := &MockHTMLGenerator{ctrl: ctrl}
	mock.recorder = &MockHTMLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTMLGenerator) EXPECT() *MockHTMLGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockHTMLGenerator) Generate(spec *domain.Specification) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", spec)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockHTMLGeneratorMockRecorder) Generate(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockHTMLGenerator)(nil).Generate), spec)
}

// GenerateFile mocks base method.
func (m *MockHTMLGenerator) GenerateFile(spec *domain.Specification, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFile", spec, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateFile indicates an expected call of GenerateFile.
func (mr *MockHTMLGeneratorMockRecorder) GenerateFile(spec, outputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFile", reflect.TypeOf((*MockHTMLGenerator)(nil).GenerateFile), spec, outputPath)
}

// MockHTMLBuilder is a mock of HTMLBuilder interface.
type MockHTMLBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockHTMLBuilderMockRecorder
	isgomock struct{}
}

// MockHTMLBuilderMockRecorder is the mock recorder for MockHTMLBuilder.
type MockHTMLBuilderMockRecorder struct {
	mock *MockHTMLBuilder
}

// NewMockHTMLBuilder creates a new mock instance.
func NewMockHTMLBuilder(ctrl *gomock.Controller) *MockHTMLBuilder {
	mock := &MockHTMLBuilder{ctrl: ctrl}
	mock.recorder = &MockHTMLBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTMLBuilder) EXPECT() *MockHTMLBuilderMockRecorder {
	return m.recorder
}

// AddFromSpec mocks base method.
func (m *MockHTMLBuilder) AddFromSpec(spec *domain.Specification) *htmlgen.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFromSpec", spec)
	ret0, _ := ret[0].(*htmlgen.Builder)
	return ret0
}

// AddFromSpec indicates an expected call of AddFromSpec.
func (mr *MockHTMLBuilderMockRecorder) AddFromSpec(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFromSpec", reflect.TypeOf((*MockHTMLBuilder)(nil).AddFromSpec), spec)
}

// Build mocks base method.
func (m *MockHTMLBuilder) Build(outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockHTMLBuilderMockRecorder) Build(outputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockHTMLBuilder)(nil).Build), outputPath)
}
