// Code generated by MockGen. DO NOT EDIT.
// Source: formatter.go
//
// Generated by this command:
//
//	mockgen -source=formatter.go -destination=mocks/mock_formatter.go -package=mocks ValidationFormatter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	validator "github.com/jycamier/promener/internal/validator"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationFormatter is a mock of ValidationFormatter interface.
type MockValidationFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockValidationFormatterMockRecorder
	isgomock struct{}
}

// MockValidationFormatterMockRecorder is the mock recorder for MockValidationFormatter.
type MockValidationFormatterMockRecorder struct {
	mock *MockValidationFormatter
}

// NewMockValidationFormatter creates a new mock instance.
func NewMockValidationFormatter(ctrl *gomock.Controller) *MockValidationFormatter {
	mock := &MockValidationFormatter{ctrl: ctrl}
	mock.recorder = &MockValidationFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationFormatter) EXPECT() *MockValidationFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockValidationFormatter) Format(result *validator.ValidationResult) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", result)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Format indicates an expected call of Format.
func (mr *MockValidationFormatterMockRecorder) Format(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockValidationFormatter)(nil).Format), result)
}
