// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/mock_validator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/jycamier/promener/internal/domain"
	validator "github.com/jycamier/promener/internal/validator"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecValidator is a mock of SpecValidator interface.
type MockSpecValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSpecValidatorMockRecorder
	isgomock struct{}
}

// MockSpecValidatorMockRecorder is the mock recorder for MockSpecValidator.
type MockSpecValidatorMockRecorder struct {
	mock *MockSpecValidator
}

// NewMockSpecValidator creates a new mock instance.
func NewMockSpecValidator(ctrl *gomock.Controller) *MockSpecValidator {
	mock := &MockSpecValidator{ctrl: ctrl}
	mock.recorder = &MockSpecValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecValidator) EXPECT() *MockSpecValidatorMockRecorder {
	return m.recorder
}

// ValidateAndExtract mocks base method.
func (m *MockSpecValidator) ValidateAndExtract(cuePath string) (*domain.Specification, *validator.ValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndExtract", cuePath)
	ret0, _ := ret[0].(*domain.Specification)
	ret1, _ := ret[1].(*validator.ValidationResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAndExtract indicates an expected call of ValidateAndExtract.
func (mr *MockSpecValidatorMockRecorder) ValidateAndExtract(cuePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndExtract", reflect.TypeOf((*MockSpecValidator)(nil).ValidateAndExtract), cuePath)
}
