// <auto-generated>
// This code was generated by Promener
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Microsoft.Extensions.DependencyInjection;

namespace metrics
{
    /// <summary>
    /// Extension methods for registering metrics in dependency injection container
    /// </summary>
    public static class MetricsServiceCollectionExtensions
    {
        /// <summary>
        /// Adds metrics services to the dependency injection container
        /// </summary>
        public static IServiceCollection AddMetrics(this IServiceCollection services)
        {
            // Register the main registry as singleton
            services.AddSingleton<MetricsRegistry>();
            // Register Http.Server metrics
            services.AddSingleton<IHttpServerMetrics>(sp =>
                sp.GetRequiredService<MetricsRegistry>().HttpServer);
            // Register Db.Postgres metrics
            services.AddSingleton<IDbPostgresMetrics>(sp =>
                sp.GetRequiredService<MetricsRegistry>().DbPostgres);

            return services;
        }
    }
}
